spring:
  application:
    name: registry-service   # ESTE NOMBRE debe coincidir con el nombre del archivo en config-repo

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
